Gemfile:
  optional:
    ':extra':
      - gem: 'plist'
        version: '~> 3.0.0'
    ':testextra':
      - gem: 'rspec-mocks'
      - gem: 'rspec-expectations'
spec/spec_helper.rb:
  mock_with: ':rspec'
